// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SV_backend.Infrastructure.Data.Context;

#nullable disable

namespace SV_backend.Migrations
{
    [DbContext(typeof(SvDbContext))]
    [Migration("20260915162527_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SV_backend.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Camisetas",
                            Slug = "camisetas"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Calças",
                            Slug = "calcas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Casacos & Jaquetas",
                            Slug = "casacos-jaquetas"
                        });
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProdutoVariacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoVariacaoId");

                    b.ToTable("PedidoItems", (string)null);
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Ativo = true,
                            CategoriaId = 1,
                            Nome = "Camiseta Oversized Minimalist",
                            PrecoBase = 129.90m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Ativo = true,
                            CategoriaId = 2,
                            Nome = "Calça Chino Slim Fit",
                            PrecoBase = 249.90m
                        });
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.ProdutoVariacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("ProdutoVariacoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            Cor = "Preto",
                            Estoque = 15,
                            ProdutoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SKU = "CAM-OVR-BLK-P",
                            Tamanho = "P"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            Cor = "Preto",
                            Estoque = 30,
                            ProdutoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SKU = "CAM-OVR-BLK-M",
                            Tamanho = "M"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            Cor = "Preto",
                            Estoque = 20,
                            ProdutoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SKU = "CAM-OVR-BLK-G",
                            Tamanho = "G"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            Cor = "Off-White",
                            Estoque = 25,
                            ProdutoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SKU = "CAM-OVR-WHT-M",
                            Tamanho = "M"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            Cor = "Khaki",
                            Estoque = 10,
                            ProdutoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SKU = "CAL-CHN-KHK-40",
                            Tamanho = "40"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333306"),
                            Cor = "Khaki",
                            Estoque = 12,
                            ProdutoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SKU = "CAL-CHN-KHK-42",
                            Tamanho = "42"
                        });
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("SV_backend.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("SV_backend.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SV_backend.Domain.Entities.ProdutoVariacao", "ProdutoVariacao")
                        .WithMany()
                        .HasForeignKey("ProdutoVariacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("ProdutoVariacao");
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.Produto", b =>
                {
                    b.HasOne("SV_backend.Domain.Entities.Categoria", "categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.ProdutoVariacao", b =>
                {
                    b.HasOne("SV_backend.Domain.Entities.Produto", "Produto")
                        .WithMany("Variacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("SV_backend.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
